### ISSUE TITLE
"ReferenceError: stream is not defined"

### ISSUE THREAD

**Issue by ScorelessPine** [ScroogeD2/owmidiconverter#9]
When attempting to use the midi found at the download site from this flat.io page ( https://flat.io/score/5980abffa66c354ca38dfb56-starmachine2000-duet-for-piano ), the program throws an error in the script info box: "An error occurred. Please check the console: F12 (Firefox) or Ctrl+Shift+J (Chrome)."

When checking the developer log, chrome follows this error chain: 
ReferenceError: stream is not defined
    at o (midi-parser.js:79)
    at r (midi-parser.js:54)
    at Object.t.exports [as parseMidi] (midi-parser.js:16)
    at new t (Midi.ts:47)
    at FileReader.reader.onload (converter:200)

I'm not sure whether this is something you can actually control or fix as it might be on the browser's end or something.

**Comment by ScroogeD2** [comment]
This is a bug with Tonejs/Midi, the library I use to process MIDI files. The bug has been fixed in a library they use for parsing/writing, but their own files don't have the fix yet. [I've notified them of the fix](https://github.com/Tonejs/Midi/issues/101), but don't know if or when they'll implement it.

**Comment by ScroogeD2** [comment]
Now fixed in Tonejs/Midi, and the file converts correctly.
